engines:
  duplication:
    enabled: true
    config:
      languages:
        - "ruby"
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-50  # Needs bumped to 0.51 when it is released

ratings:
  paths:
    - "Gemfile.lock"
    - "**.rb"

exclude_paths:
  - "spec/**/*.rb"
